### ISSUE TITLE
Corp Customs Office table not updating

### ISSUE THREAD

**Issue by IvandaNothabeer** [Yapeal/yapeal#104]
Corp Customs Office records cannot be saved in the MySQL database due to incorrect boolean value ("True") for 'allowAlliance' ( should be "1" )

```
[2016-05-05 06:31:04] yapeal.WARNING: Failed to upsert data from Eve API corp/CustomsOffices for 673319797 {"exception":"[object] (P
DOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'True' for column 'allowAlliance' at row 1 at C:\\inetpub\\wwwroot\\tycoon\\protected\\vendors\\yapeal\\lib\\Database\\EveApiToolsTrait.php:113)"} []
```

**Comment by IvandaNothabeer** [comment]
Problem is due to a change introduced in MySQL version 5.6

You need to disable MySQL Strict Mode in the server configuration

https://support.kayako.com/article/472-how-do-i-disable-mysql-strict-mode-on-the-server

**Comment by Dragonrun1** [comment]
Any time that the 'solution' involve disabling strict mode you have not understood the actual problem ;-) The problem we are running up against here is first that MySQL doesn't have an actual Boolean datatype and instead uses a tinyint instead :-P The second thing is CCP is not very consistent with what they do for Boolean either so you never know what you get as well in the APIs and you need to be able to test each API directly for this and other issues. I haven't been in any Corps that owned Customs Office so this API is largely been untested and bug reports like this one is the only way I find out about issues. For a comparison look at ```allowAllianceMembers``` from the general settings in StarbaseDetails which serves the same function but  works fine.

I'll look into a fix but I'm in the processing of moving so it may be a few days before I get a real chance to work on it.

**Comment by Dragonrun1** [comment]
Going to archive the project as I'm no longer working on it nor will support it in the future.
