### ISSUE TITLE
LocationID returns negative number

### ISSUE THREAD

**Issue by IvandaNothabeer** [Yapeal/yapeal#105]
MemberTrackingExtended API call returns a negative value for "locationID" when the character is docked in a Citadel. the "location" is blank.

The data is rejected as invalid and no values are stored in the member tracking table.

`[2016-05-05 06:57:05] yapeal.DEBUG: Started network retrieve for corp/MemberTracking [] []
[2016-05-05 06:57:07] yapeal.INFO: Could NOT find C:/inetpub/wwwroot/tycoon/protected/vendors/yapeal/lib/Database/Corp/MemberTrackin
g.xsl [] []
[2016-05-05 06:57:07] yapeal.DEBUG: Given XSL name C:/inetpub/wwwroot/tycoon/protected/vendors/yapeal/lib/Database/common.xsl [] []
[2016-05-05 06:57:07] yapeal.DEBUG: Started XSD validating [] []
[2016-05-05 06:57:07] yapeal.DEBUG: Element 'row', attribute 'locationID': [facet 'minInclusive'] The value '-1168819770' is less th
an the minimum value allowed ('-1').  [] []`

**Comment by IvandaNothabeer** [comment]
Modify 'Database\corp\MemberTracking.xsd' line 16 as follows

`<xs:attribute type="xs:long" name="locationID"/>`

**Comment by IvandaNothabeer** [comment]
Modify "\Database\Corp\MemberTracking.xsd" line 16 as follows ...

`<xs:attribute type="xs:long" name="locationID"/>`

**Comment by Dragonrun1** [comment]
Just changing the XSL doesn't fix it the DB schema would also need to be changed as it's currently ```"locationID"     BIGINT(20) UNSIGNED DEFAULT 0,```.

Just to make sure I'm remembering right since I don't play much any more is the Citadel you are talking about in wormhole space?

**Comment by IvandaNothabeer** [comment]
You're correct. Apparently I did this also during troubleshooting.

No the citadel is in Null.

**Comment by Dragonrun1** [comment]
Just another question for you: are you running a 32 or 64 bit version for PHP and MySql?

**Comment by IvandaNothabeer** [comment]
Apparently its an API bug

**Comment by Dragonrun1** [comment]
I was kind of wondering about that. You have any reference to where you found that out?

**Comment by IvandaNothabeer** [comment]
#devfleet slack channel.
