### ISSUE TITLE
PHP Warning: Invalid Schema: AbstractCommonEveApi.php line 356

### ISSUE THREAD

**Issue by Melikoth** [Yapeal/yapeal#96]
Recently started with a fresh installation containing only a corp key. While updating from the command line I received the following warnings. The PHP Warning appears prior to any other script output and the yapeal warning appears to be from the parsing of StarbaseDetail.xsl. The first appears all the time, the second only with error threshold <400.

PHP Warning:  DOMDocument::schemaValidate(): Invalid Schema in ...lib\Database\AbstractCommonEveApi.php on line 356

yapeal.WARNING: The data retrieved from Eve API corp/StarbaseDetail for 502319709 is invalid [] []

**Comment by Dragonrun1** [comment]
could you sent copy of log to my github Email and I'll take a look. Set logging to 100 pls if you would.

**Comment by Melikoth** [comment]
I sent that in, not sure if you got it or if I sent to the wrong address.

**Comment by Dragonrun1** [comment]
Didn't seem to receive it could you resend it to me?

**Comment by Melikoth** [comment]
Sure, just resent them.

**Comment by Melikoth** [comment]
After updating it appears the issue has been resolved.  I ran yapeal from the command line about ten times but received no warnings and no log file was created with a threshold of 300.
The cache is now populating with StarbaseDetail*.xml's and many others.

**Comment by Dragonrun1** [comment]
Okay going to close issue then since it seems to be fixed.
